name = "atlantium-group-og-worker"
main = "group-og-worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "atlantium.ai/groups/*", zone_name = "atlantium.ai" }
]

# For development/testing
# [env.dev]
# name = "atlantium-group-og-worker-dev"
